version: '3.8'
services:
  wscontroller:
    build: 
      context: ./controller
      dockerfile: Dockerfile
    container_name: wscontroller
    environment:
      - AUTH_TOKEN
    restart: always
  wsnode:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: wsnode
    environment:
      - AUTH_TOKEN
    restart: always
